### ISSUE TITLE
Transfer from contributor to bot

### ISSUE THREAD

**Issue by UnknownUser2222** [UnknownUser2222/pycor#16]
Generated by UnknownUser2222
At Friday, 4 November 2022 on 1:00:00 PM, this transfer from contributor to bot has shall succeed.
You must follow its code of conduct when proceeding this.
All rules of the code of conduct will apply.
The contributor of @NSCPyCor will be proceeded to transfer to bot and shall delete all of the person's repositories, codespaces, gists, config files and more when this person comments `transfer bot @NSCPyCor`.
This contributor @NSCPyCor will have its new username, @UnknownUser with any number or letter.
Please be certain. Do not put any username except @NSCPyCor because any contributor(s) will convert into a bot.

**Comment by NSCPyCor** [comment]
`transfer bot @NSCPyCor`
I understand the consequences, convert to bot

**Comment by UnknownUser2222** [comment]
You are now a bot.
You can revert before Jan 1, 2023 by typing `revert contributor @NSCPyCor`
All your data has been successfully deleted.
If you type `revert contributor @NSCPyCor` after Jan 1, 2023, it won't work. You need to create a new account to contribute again
