### ISSUE TITLE
Transfer from contributor to bot

### ISSUE THREAD

**Issue by UnknownUser2222** [UnknownUser2222/pycor#17]
Generated by UnknownUser2222
At Friday, 4 November 2022 on 1:00:00 PM, this transfer from contributor to bot has shall succeed.
You must follow its code of conduct when proceeding this.
All rules of the code of conduct will apply.
The contributor of @NSCPyCor will be proceeded to transfer to bot and shall delete all of the person's repositories, codespaces, gists, config files and more when this person comments transfer bot @NSCPyCor.
This contributor @NSCPyCor will have its new username, @UnknownUser with any number or letter.
Please be certain. Do not put any username except @NSCPyCor because any contributor(s) will convert into a bot.

**Comment by NSCPyCor** [comment]
`transfer bot @NSCPyCor`
I understand the consequences, convert to bot

**Comment by UnknownUser2222** [comment]
You are now a bot.
You can revert before Jan 1, 2023 by typing `revert contributor @NSCPyCor`
All your data has been successfully deleted.
If you type `revert contributor @NSCPyCor` after Jan 1, 2023, it won't work. You need to create a new account to contribute again

**Comment by NSCPyCor** [comment]
`temp revert contributor @NSCPyCor until 11/06/2022`

I need to revert for 1 day, because I need to export my data before it's permanently deleted on Jan 1, 2023. Please accept this @UnknownUser2222

**Comment by UnknownUser2222** [comment]
You are now a contributor until 11/06/2022. You can extend the date or permanently convert back into a contributor until 01/01/2022 by typing `extend temp revert contributor @NSCPyCor to 12/34/5678` to extend or to permanently convert into contributor by typing `permanent revert contributor @NSCPyCor`. You can always go back to bot by typing `transfer bot @NSCPyCor`. Feel free to chat.

**Comment by NSCPyCor** [comment]
`superposition @NSCPyCor contributor with autowdaguttillity perm`
`permanent revert contributor @NSCPyCor`
Export done revert back

**Comment by UnknownUser2222** [comment]
Hold on, did you use Linux terminal to DO THIS!?!
😲 😲 😲

**Comment by NSCPyCor** [comment]
Yes

**Comment by UnknownUser2222** [comment]
Oh you are good at that.
