### ISSUE TITLE
100th commit

### ISSUE THREAD

**Issue by UnknownUser2222** [UnknownUser2222/pycor#18]
It has been 25 days since our first commit. Now, this is our 100th commit. Who WILL do the 100th commit?

Qualified:
1. @UnknownUser1837 
2. @UnknownUser2129 
3. @NSCPyCor 
4. @UnknownUser9561 
5. @UnknownUser2222 
Chances are MEDIUM; 1 in 6 odds you will do it.

The 100th commit will be from @NSCPyCor!

**Comment by NSCPyCor** [comment]
Thanks!!!
